"""
Bake the light gun model into a C++ header for the headset build (hotd2-vr).

    python convert_gun.py <model.glb> <out.h> [preview.png]

Model: "Namco Arcade Gun" by Martoscar,
https://sketchfab.com/3d-models/namco-arcade-gun-15fbd5b9add94a34b5c21746e3dd32be
licensed CC BY 4.0 (http://creativecommons.org/licenses/by/4.0/). The header keeps the
credit. Changes: re-oriented and moved into the controller's aim space, recoloured,
textures dropped.

Gun space (see core/rend/vr/xr_gun.h): the controller's aim pose, metres, -z forward
along the barrel, +y up, +x right. The model has its barrel along +x and +y up, at real
size (25 cm). The app puts its grip in the hand and scales it at runtime (gunPlacement in
core/rend/vr/xr_gun.h, vr.GunScale).
"""
import sys
import numpy as np
from glb import load

# A model point on the front of the grip at middle-finger height (not the web of the hand,
# as this used to say), and where it goes. Kept as baked: xr_gun.h's ModelPalm is measured
# against this placement.
GRIP_ANCHOR = np.array([-0.072, -0.030, 0.0])
GRIP_TARGET = np.array([0.0, -0.022, 0.050])
# Centre of the front lens (the "muzzle"): shots and the aim line start here.
LENS_CENTRE = np.array([0.1181, 0.0391, 0.0])
POS_SCALE = 1e-5    # positions are stored as int16 in units of 10 micrometres

PARTS = ['hardsurfaces_2', 'softsurfaces_1', 'screws_3', 'lens_4']


def to_gun(p):
    """Model (x forward, y up, z side) -> gun space (-z forward, y up, x right)."""
    q = p - GRIP_ANCHOR
    return np.stack([q[..., 2], q[..., 1], -q[..., 0]], axis=-1) + GRIP_TARGET


def to_gun_dir(n):
    return np.stack([n[..., 2], n[..., 1], -n[..., 0]], axis=-1)


def main():
    parts, _ = load(sys.argv[1])
    by_name = {p['name']: p for p in parts}
    positions, normals, indices, ranges = [], [], [], []
    base = 0
    for name in PARTS:
        p = by_name[name]
        positions.append(to_gun(p['pos']))
        normals.append(to_gun_dir(p['nrm']))
        first = sum(len(i) for i in indices)
        indices.append((p['tri'] + base).reshape(-1))
        ranges.append((name.split('_')[0], first, len(p['tri']) * 3))
        base += len(p['pos'])
    pos = np.vstack(positions)
    nrm = np.vstack(normals)
    idx = np.concatenate(indices)
    assert base < 65536, 'too many vertices for 16-bit indices'
    assert np.abs(pos).max() / POS_SCALE < 32767
    muzzle = to_gun(LENS_CENTRE)
    print('vertices', base, 'triangles', len(idx) // 3)
    print('bounds', pos.min(0).round(3), pos.max(0).round(3), 'muzzle', muzzle.round(4))

    qp = np.round(pos / POS_SCALE).astype(np.int32)
    qn = np.clip(np.round(nrm * 127), -127, 127).astype(np.int32)

    def rows(values, per_line):
        flat = values.reshape(-1)
        return ',\n'.join(','.join(str(v) for v in flat[i:i + per_line]) for i in range(0, len(flat), per_line))

    with open(sys.argv[2], 'w', newline='\n') as f:
        f.write('// SPDX-License-Identifier: CC-BY-4.0\n')
        f.write('// Generated by hotd2-vr/gun_model/convert_gun.py - do not edit.\n')
        f.write('//\n')
        f.write('// "Namco Arcade Gun" by Martoscar (https://sketchfab.com/Martoscar)\n')
        f.write('// https://sketchfab.com/3d-models/namco-arcade-gun-15fbd5b9add94a34b5c21746e3dd32be\n')
        f.write('// licensed CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/).\n')
        f.write('// Changed: re-oriented and moved into the controller\'s aim space, quantised (16-bit\n')
        f.write('// positions, 8-bit normals), textures and materials dropped (the colours are set in\n')
        f.write('// xr_gun.cpp). This adaptation (c) 2026 mikermak, also under CC BY 4.0.\n')
        f.write('#pragma once\n\nnamespace vr::xr::gunmodel\n{\n\n')
        f.write(f'constexpr float PositionScale = {POS_SCALE}f;\t// metres per position unit\n')
        f.write(f'constexpr float Muzzle[3] = {{ {muzzle[0]:.5f}f, {muzzle[1]:.5f}f, {muzzle[2]:.5f}f }};\n\n')
        f.write('struct Part { const char *name; unsigned first, count; };\t// ranges of Indices\n')
        f.write('constexpr Part Parts[] = {\n')
        for name, first, count in ranges:
            f.write(f'\t{{ "{name}", {first}u, {count}u }},\n')
        f.write('};\n\n')
        f.write(f'constexpr unsigned VertexCount = {base};\n')
        f.write('// x, y, z\n')
        f.write('constexpr short Positions[] = {\n' + rows(qp, 30) + '\n};\n')
        f.write('// x, y, z, times 127\n')
        f.write('constexpr signed char Normals[] = {\n' + rows(qn, 48) + '\n};\n')
        f.write('constexpr unsigned short Indices[] = {\n' + rows(idx, 36) + '\n};\n\n}\n')

    if len(sys.argv) > 3:
        from preview import render
        from PIL import Image
        colors = {'hardsurfaces': (205, 22, 18), 'softsurfaces': (150, 10, 10), 'screws': (70, 70, 75), 'lens': (40, 8, 8)}
        gun_parts = [{'pos': to_gun(by_name[n]['pos']), 'tri': by_name[n]['tri']} for n in PARTS]
        cols = [colors[n.split('_')[0]] for n in PARTS]
        # side view: -z (forward) to the right is x axis -z; use (z, y) with forward to the left
        views = [((2, 1, 0), 'side: forward is left'), ((0, 2, 1), 'top: forward is up... (x,z)'), ((0, 1, 2), 'from behind (x,y)')]
        imgs = [render(gun_parts, ax, colors=cols, title=t) for ax, t in views]
        sheet = Image.new('RGB', (700 * 3, 700))
        for i, im in enumerate(imgs):
            sheet.paste(im, (700 * i, 0))
        sheet.save(sys.argv[3])


if __name__ == '__main__':
    main()
